version: '2'

services:
  phonebook-mysql:
    container_name: phonebook-mysql
     volumes:
       - crud_db_data:/var/lib/mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always

  phonebook-app:
    container_name: phonebook-app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - phonebook-mysql
    ports:
      - "8181:8181"
    restart: always
    
volumes:
    crud_db_data:
